server:
  port: 9000


spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/budget
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true


